name: CI

on: 
    push:
      branches:
        - main

jobs:
  my_test:
    runs-on: ubuntu-latest
    needs: [my_deploy]
    steps:
    -  name: Print hello
       run: echo "Hello, it's test"
         
  my_deploy:
    runs-on: ubuntu-latest

    steps:
    -  name: Print deploy
       run: echo "Hello, it's deploy"
