name: CI

on: 
    push:
      branches:
        - main


jobs:
#   my_test:
#     runs-on: ubuntu-latest
    
#     steps:
#     -  name: Print hello
#        run: echo "Hello, it's test"

#   install_python:
#     runs-on: ubuntu-latest
#     needs: [my_test]
#     steps:
#     -  name: Install python
#        run: sudo apt-get install python3
#     -  name: Check version
#        run: python3 --version
       
#   my_deploy:
#     runs-on: ubuntu-latest
#     needs: [install_python]

#     steps:
#     -  name: Print deploy
#        run: echo "Hello, it's deploy"

  yearnow:
    runs-on: ubuntu-latest
    # needs: [my_deploy]
    steps:
    -  name: Get current date
       run: echo "YEARIS=$(date +'%Y-%m-%dT%H:%M:%S')}" >> $GITHUB_ENV
    -  name: Show date
       run: echo "Date is $YEARIS"
       
  yearnowwithtimezone:
    runs-on: ubuntu-latest
    
    steps:
      - name: Set timezone
        uses: szenius/set-timezone@v1.1
        with:
          timezoneLinux: "Asia/Almaty"
         
      - name: Date with timezone
        run: echo "Date with timezone $(date +'%Y-%m-%dT%H:%M:%S')}"
