name: CI

on: 
    push:
      branches:
        - main

env:
    YEAR_IS: "2020-10-07T12:00:00+01:00"

jobs:
  my_test:
    runs-on: ubuntu-latest
    
    steps:
    -  name: Print hello
       run: echo "Hello, it's test"

  install_python:
    runs-on: ubuntu-latest
    needs: my_test
    steps:
    -  name: Install python
       run: sudo apt-get install python3

  check_version:
    runs-on: ubuntu-latest
    needs: install_python
    
    steps:
    -  name: Check version
       run: python3 --version
       
  my_deploy:
    runs-on: ubuntu-latest
    needs: check_version

    steps:
    -  name: Print deploy
       run: echo "Hello, it's deploy"

  yearnow:
    runs-on: ubuntu-latest

    steps:
    -  name: Get current date
       run: echo ${{ env.YEAR_IS }}
